### ISSUE TITLE
16:10 screen cropping issue

### ISSUE THREAD

**Issue by JimmyMultani** [Kaldaien/TZF#13]
Hello!

I'm running ToZ on a 1920x1200 screen and whenever I open a menu screen, it seems to assume that I'm running a 1920x1080 monitor.

If I'm doing something wrong, I apologize in advance.

Thanks!

![2015-11-21_00001](https://cloud.githubusercontent.com/assets/1281284/11321008/33b8f538-907d-11e5-9cd2-da1fd0c50065.jpg)
![2015-11-21_00002](https://cloud.githubusercontent.com/assets/1281284/11321007/33b86618-907d-11e5-8fad-1961b9a18e30.jpg)

**Comment by drdaxxy** [comment]
The game normally doesn't support aspect ratios other than 16:9 properly - it just stretches everything. At 16:10, this isn't very noticeable, but on ultrawide/multi-monitor setups (21:9 and beyond) it's absolutely unacceptable. TZFix corrects this, making menus and HUD show in the center 16:9 box of the screen. If you don't want that, turn AspectCorrection and AspectCorrectVideos off in tzfix.ini.

**Comment by JimmyMultani** [comment]
That did it! Thanks!

**Comment by Kaldaien** [comment]
Quite the opposite, the game realizes you are NOT running on a 16:9 monitor and then it letterboxes the UI rather than stretching it. If I had more time to devote to this task, I'd properly clear the top and bottom part to black instead of displaying that garbage.

<hr>

I am re-opening this, because I (or possibly someone else) need to improve widescreen support. The feature was never fully implemented and it has taken a back-seat ever since 60 FPS was introduced.

**Comment by Kaldaien** [comment]
1.1.4 clears the purple garbage from the sides, and I'm happy to close this.
